# Generated by Django 5.0.1 on 2024-02-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('userid', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='身份证')),
                ('username', models.CharField(max_length=10, verbose_name='姓名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
                'db_table': 'parking_admin_info',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=40)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '社区消息通知',
                'verbose_name_plural': '社区消息通知',
                'db_table': 'messages',
            },
        ),
    ]
