# Generated by Django 5.0.1 on 2024-01-12 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('address', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('water', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('gas', models.IntegerField()),
            ],
            options={
                'verbose_name': '住房信息',
                'verbose_name_plural': '住房信息',
                'db_table': 'address_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=465)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.addressinfo')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
    ]
