# Generated by Django 5.0.1 on 2024-01-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[(0, '男'), (1, '女')], default='男', max_length=2),
        ),
    ]
